analyzer:
  errors:
  missing_required_param: error
  avoid_print: error
  prefer_single_quotes: warn
  prefer_const_constructors: error
  prefer_const_declarations: error
  exhaustive_cases: error
  file_names: error
  avoid_empty_else: error
  unnecessary_statements: error

linter:
  rules:
    missing_required_param: true
    avoid_print: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    exhaustive_cases: true
    file_names: true
    avoid_empty_else: true
    unnecessary_statements: true

include: package:flutter_lints/flutter.yaml
# https://dart-lang.github.io/linter/lints/index.html.

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
