name: Linting

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.7.8'

    - name: Check for linting errors
      run: flutter analyze --no-pub --custom-rules=analysis_options.yaml
