name: Flutter Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.x.x' # Replace with the version of Flutter you're using

    - name: Install dependencies
      run: flutter pub get

    - name: Run unit tests
      run: flutter test
